version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/cli"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/desktop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "poetry"
    directory: "/docs"
    schedule:
      interval: "weekly"