[tool.poetry]
name = "onionshare"
version = "2.2"
description = "Securely and anonymously send and receive files, and publish onion sites"
authors = ["Micah Lee <micah@micahflee.com>"]
license = "GPLv3+"

[tool.poetry.dependencies]
python = "^3.6"
Click = "*"
Flask = "*"
Flask-HTTPAuth = "*"
pycryptodome = "*"
PyQt5 = "5.14.0"
PyQt5-sip = "*"
PySocks = "*"
requests = "*"
stem = "*"

[tool.poetry.dev-dependencies]
atomicwrites = "*"
attrs = "*"
more-itertools = "*"
pluggy = "*"
py = "*"
pytest = "*"
pytest-faulthandler = "*"
pytest-qt = "*"
six = "*"
urllib3 = "*"
pyinstaller = {version = "*", platform = "darwin"}
setuptools = {version = "*", platform = "windows"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
