#!/bin/bash

# Designed for Linux for now
while getopts ":lh" opt; do
  case $opt in
    h) HEADLESS=True
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done


if [[ $HEADLESS ]]; then
  # Run via XVFB and silence a lot of noise
  echo "Running headless tests..."
  xvfb-run py.test-3 | egrep -v "QPainter|QWidget"
  if [ ${PIPESTATUS[0]} -ne 0 ]; then
    exit 1
  else
    exit 0
  fi
else
  py.test-3
fi
