#!/bin/bash

# Designed for Linux for now

if [[ $1 = "--headless" ]]; then
  # Run via XVFB and silence a lot of noise
  xvfb-run python3 /usr/lib/python3/dist-packages/pytest.py -k 'not test_starts_with_empty_strings' | egrep -v "QPainter|QWidget"
else
  python3 /usr/lib/python3/dist-packages/pytest.py -k 'not test_starts_with_empty_strings'
fi
if [ ${PIPESTATUS[0]} -ne 0 ]; then
  exit 1
else
  exit 0
fi
