#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OnionShare | https://onionshare.org/

Copyright (C) 2017 Micah Lee <micah@micahflee.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
try:
    # try to use module installed on system first
    import onionshare
except ImportError:
    # use module provided by source repository
    import os, sys, inspect
    # path used to call the executable
    relative_exec_path = inspect.getfile(inspect.currentframe())
    # split off path to executable
    path_to_executable = os.path.split(relative_exec_path)[0]
    # make sure no symlinks fool the procedure
    real_path = os.path.realpath(os.path.abspath(path_to_executable))
    # strip out the install/scripts part
    module_folder = path_to_executable.replace('/install/scripts', '')
    # insert module into path
    if module_folder not in sys.path:
        sys.path.insert(0, module_folder)
    # try importing again
    import onionshare

onionshare.main()
