name: Build
run-name: Build snap
on:
  push:
    branches:
      - snap-ci

jobs:
  build-snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo snap install snapcraft --classic
      - run:
          snapcraft
