name: Build Windows
run-name: Build win32 and win64
on:
  push:
    branches:
      - github-actions

jobs:
  build-win64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: ~\.cache\AppData\Local\pypoetry\Cache\virtualenvs
          key: ${{ runner.os }}-win64-${{ hashFiles('desktop/poetry.lock') }}

      - name: Install poetry
        run: C:\hostedtoolcache\windows\Python\3.9.13\x64\python -m pip install poetry

      - name: Explore
        shell: pwsh
        run: |
          which poetry

      - name: Install poetry dependencies
        run: cd desktop && poetry install

      - uses: actions/cache@v3
        with:
          path: desktop\build\tor
          key: ${{ runner.os }}-win64-${{ hashFiles('desktop/scripts/get-tor.py') }}
      
      - name: Get tor binaries from Tor Browser (64-bit)
        run: cd desktop && poetry run python .\scripts\get-tor.py win64
