name: Run Tests
run-name: Run tests 🚀
on: [push]
jobs:
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install tor obfs4proxy
          pip install --upgrade pip poetry
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-cli-poetry-${{ hashFiles('cli/poetry.lock') }}
      - run: cd cli && poetry install
      - run: |
          cd cli
          poetry run pytest -v ./tests
          poetry run onionshare-cli --local-only ./tests --auto-stop-timer 2
          poetry run onionshare-cli --local-only --receive --auto-stop-timer 2
          poetry run onionshare-cli --local-only --website ../docs --auto-stop-timer 2
          poetry run onionshare-cli --local-only --chat --auto-stop-timer 2
